// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtayrlqyrqqkiyrkptoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YXlybHF5cnFxa2l5cmtwdG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDgxMjcsImV4cCI6MjA1NTEyNDEyN30.sZFqymc6-uBDOcuMdzpsI-ypY4jqGsjpXoy0T-ca-8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);